#!/bin/bash

echo "🧪 Testing Stripe Webhook"
echo "=========================="
echo ""
echo "Your webhook endpoint:"
echo "https://gnoknthlsubjmigmbecy.supabase.co/functions/v1/stripe-webhook"
echo ""
echo "✅ Setup Status:"
echo "  - Webhook Secret: SET"
echo "  - JWT Verification: DISABLED"
echo "  - Function: ACTIVE"
echo ""
echo "📋 To test:"
echo ""
echo "1. Go to Stripe Dashboard:"
echo "   https://dashboard.stripe.com/test/webhooks"
echo ""
echo "2. Find your webhook endpoint (or create it if needed)"
echo ""
echo "3. Click 'Send test webhook'"
echo ""
echo "4. Select event: checkout.session.completed"
echo ""
echo "5. Click 'Send test webhook'"
echo ""
echo "6. Check the response - should be 200 OK"
echo ""
echo "7. View logs here:"
echo "   https://supabase.com/dashboard/project/gnoknthlsubjmigmbecy/functions/stripe-webhook/logs"
echo ""
echo "You should see logs like:"
echo "  🌍 Stripe Webhook is running..."
echo "  Received event: checkout.session.completed"
echo "  ✅ Webhook processed successfully"
echo ""

