#!/bin/bash

# Stripe Webhook Testing Script
# This script helps test your Stripe webhook edge function

PROJECT_ID="gnoknthlsubjmigmbecy"
WEBHOOK_URL="https://${PROJECT_ID}.supabase.co/functions/v1/stripe-webhook"

echo "🧪 Stripe Webhook Testing Helper"
echo "=================================="
echo ""
echo "Your webhook endpoint: ${WEBHOOK_URL}"
echo ""
echo "To test your webhook, you have two options:"
echo ""
echo "OPTION 1: Using Stripe CLI (Recommended)"
echo "------------------------------------------"
echo "1. Install Stripe CLI:"
echo "   Download from: https://github.com/stripe/stripe-cli/releases/latest"
echo "   Or use: brew install stripe/stripe-cli/stripe"
echo ""
echo "2. Login to Stripe:"
echo "   stripe login"
echo ""
echo "3. Forward webhooks to your endpoint:"
echo "   stripe listen --forward-to ${WEBHOOK_URL}"
echo ""
echo "4. In another terminal, trigger test events:"
echo "   stripe trigger checkout.session.completed"
echo "   stripe trigger customer.subscription.deleted"
echo ""
echo ""
echo "OPTION 2: Test via Stripe Dashboard"
echo "------------------------------------"
echo "1. Go to: https://dashboard.stripe.com/test/webhooks"
echo "2. Click 'Add endpoint'"
echo "3. Enter: ${WEBHOOK_URL}"
echo "4. Select events:"
echo "   - checkout.session.completed"
echo "   - customer.subscription.deleted"
echo "5. Click 'Add endpoint'"
echo "6. Click 'Send test webhook' to test"
echo ""
echo ""
echo "OPTION 3: Check Webhook Logs"
echo "-----------------------------"
echo "View logs in Supabase Dashboard:"
echo "https://supabase.com/dashboard/project/${PROJECT_ID}/functions/stripe-webhook/logs"
echo ""

